synerise_integration_admin_channel_configuration:
    resource: |
        alias: synerise_integration.channel_configuration
        section: admin
        templates: "@SyliusAdmin/Crud"
        grid: synerise_integration_admin_channel_configuration
        form:
            type: Synerise\SyliusIntegrationPlugin\Form\Type\ChannelConfigurationType
        permission: true
        vars:
            all:
                header: synerise_integration.ui.channel_configurations
                subheader: synerise_integration.ui.manage_channel_configurations
                breadcrumb: synerise_integration.ui.channel_configurations
            index:
                icon: cogs
        path: /synerise/configuration
    type: sylius.resource
synerise_integration_admin_synchronization_configuration:
    resource: |
        alias: synerise_integration.synchronization_configuration
        section: admin
        templates: "@SyliusAdmin/Crud"
        grid: synerise_integration_admin_synchronization_configuration
        form:
            type: Synerise\SyliusIntegrationPlugin\Form\Type\SynchronizationConfigurationType
        permission: true
        vars:
            all:
                header: synerise_integration.ui.synchronization
                subheader: synerise_integration.ui.manage_synchronization
                breadcrumb: synerise_integration.ui.synchronization
            index:
                icon: cogs
        path: /synerise/synchronization_configuration
    type: sylius.resource
synerise_integration_admin_workspace:
    resource: |
        alias: synerise_integration.workspace
        section: admin
        templates: "@SyliusAdmin/Crud"
        grid: synerise_integration_admin_workspace
        form:
            type: Synerise\SyliusIntegrationPlugin\Form\Type\WorkspaceType
        permission: true
        vars:
            all:
                header: synerise_integration.ui.workspace.grid.header
                subheader: synerise_integration.ui.workspace.grid.subheader
                breadcrumb: synerise_integration.ui.workspace.grid.header
            index:
                icon: cogs
        path: /synerise/workspace
    type: sylius.resource
synerise_integration_admin_synchronization:
    resource: |
        alias: synerise_integration.synchronization
        templates: "@SyliusAdmin/Crud"
        path: /synerise/synchronization_configuration/{configurationId}/synchronization
        only: ['show', 'create', 'delete']
        section: admin
    type: sylius.resource
