imports:
#    - { resource: "app/twig_hooks/**/*.yaml" }
    - { resource: "app/messenger.yaml" }
    - { resource: "resources.yaml" }

sylius_grid:
    templates:
        action:
            delete_channel_configuration: "@SyneriseSyliusIntegrationPlugin/admin/channel_configuration/grid/action/delete.html.twig"
            delete_workspace: "@SyneriseSyliusIntegrationPlugin/admin/workspace/grid/action/delete.html.twig"
            new_sync: "@SyneriseSyliusIntegrationPlugin/admin/synchronization_configuration/newSync.html.twig"
    grids:
        synerise_integration_admin_channel_configuration:
            driver:
                name: doctrine/orm
                options:
                    class: "%synerise_integration.model.channel_configuration.class%"
            fields:
                channel:
                    type: string
                    label: sylius.ui.channel
                    sortable: true
                workspace:
                    type: string
                    label: synerise_integration.ui.channel_configuration.form.workspace.label
                    sortable: true
            actions:
                main:
                    create:
                        type: create
                        label: "synerise_integration.ui.channel_configuration_create_new"
                item:
                    update:
                        type: update
                    delete:
                        type: delete_channel_configuration
                    show:
                        type: show
        synerise_integration_admin_synchronization_configuration:
            driver:
                name: doctrine/orm
                options:
                    class: "%synerise_integration.model.synchronization_configuration.class%"
            fields:
                channel:
                    type: string
                    label: sylius.ui.channel
                    sortable: true
            actions:
                main:
                    create:
                        type: create
                        label: "synerise_integration.ui.synchronization_configuration_create_new"
                item:
                    new_sync:
                        type: new_sync
                        options:
                            configurationId: resource.id
                    show:
                        type: show
                    update:
                        type: update
                    delete:
                        type: delete
        synerise_integration_admin_workspace:
            driver:
                name: doctrine/orm
                options:
                    class: "%synerise_integration.model.workspace.class%"
            fields:
                name:
                    type: string
                    label: synerise_integration.workspace.form.name.label
                    sortable: true
                environment:
                    type: twig
                    label: synerise_integration.workspace.form.environment.label
                    options:
                        template: "@SyneriseSyliusIntegrationPlugin/admin/shared/grid/field/enum.html.twig"
                authentication_method:
                    type: twig
                    label: synerise_integration.workspace.form.authentication_method.label
                    options:
                        template: "@SyneriseSyliusIntegrationPlugin/admin/shared/grid/field/enum.html.twig"
                permissionsStatus:
                    type: twig
                    label: synerise_integration.workspace.permissions_status.label
                    options:
                        template: "@SyneriseSyliusIntegrationPlugin/admin/workspace/grid/field/permissions_status.html.twig"
            actions:
                main:
                    create:
                        type: create
                        label: "synerise_integration.workspace.create.title"
                item:
                    show:
                        type: show
                    update:
                        type: update
                    delete:
                        type: delete_workspace
sylius_resource:
    resources:
        synerise_integration.channel_configuration:
            classes:
                model: Synerise\SyliusIntegrationPlugin\Entity\ChannelConfiguration
                interface: Synerise\SyliusIntegrationPlugin\Entity\ChannelConfigurationInterface
                form: Synerise\SyliusIntegrationPlugin\Form\Type\ChannelConfigurationType
                repository: Synerise\SyliusIntegrationPlugin\Repository\ChannelConfigurationRepository
        synerise_integration.synchronization_configuration:
            classes:
                model: Synerise\SyliusIntegrationPlugin\Entity\SynchronizationConfiguration
                interface: Synerise\SyliusIntegrationPlugin\Entity\SynchronizationConfigurationInterface
                form: Synerise\SyliusIntegrationPlugin\Form\Type\SynchronizationConfigurationType
                repository: Synerise\SyliusIntegrationPlugin\Repository\SynchronizationConfigurationRepository
        synerise_integration.synchronization:
            classes:
                model: Synerise\SyliusIntegrationPlugin\Entity\Synchronization
                repository: Synerise\SyliusIntegrationPlugin\Repository\SynchronizationRepository
                form: Synerise\SyliusIntegrationPlugin\Form\Type\SynchronizationType
        synerise_integration.workspace:
            classes:
                model: Synerise\SyliusIntegrationPlugin\Entity\Workspace
                interface: Synerise\SyliusIntegrationPlugin\Entity\WorkspaceInterface
                form: Synerise\SyliusIntegrationPlugin\Form\Type\WorkspaceType
monolog:
    channels: ["synerise"]
    handlers:
        synerise:
            type: stream
            path: "%kernel.logs_dir%/synerise.log"
            level: debug
            channels: ["synerise"]
